BASE=../../../..

LOCAL_CFLAGS= -I/usr/lib64/erlang/lib/erl_interface-3.7.4/include  -D_REENTRANT -I/home/kanderson/FreeSWITCH/libs/apr/include
LOCAL_LDFLAGS= -L/usr/lib64/erlang/lib/erl_interface-3.7.4/lib  -lei

include $(BASE)/build/modmake.rules
